format = """\
[\ue0b6](bg:#030B16 fg:#7DF9AA)\
[\ue711 ](bg:#7DF9AA fg:#090c0c)\
[\ue0b0](fg:#7DF9AA bg:#1C3A5E)\
$time\
[\ue0b0](fg:#1C3A5E bg:#3B76F0)\
$directory\
[\ue0b0](fg:#3B76F0 bg:#FCF392)\
$git_branch\
$git_status\
$git_metrics\
[\ue0b0](fg:#FCF392 bg:#030B16)\
$character\
"""

[directory]
format = "[ \uf07c $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "\ue65d \ue725 "
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = "\uf418 "

[cmd_duration]
format = "[ \uf43a $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ \uf43a $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'
